### PR TITLE
Support rubies 2.7, 3.0 and 3.1 in CI

### PR DESCRIPTION
**Pull request by AlfonsoUceda**
@ronwsmith I've updated the github workflow to support rubies 2.7, 3.0 and 3.1 in CI.

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
@ronwsmith let's see if everything is green ;)

**Comment by AlfonsoUceda** [comment]
@ronwsmith it seems we would need to drop old ruby versions and support it from 2.6 (included)

**Comment by ronwsmith** [comment]
@AlfonsoUceda if you can get CI green for 2.6+, I'm good bumping up that requirement.

**Comment by AlfonsoUceda** [comment]
@ronwsmith could you re-run the workflow? I do not understand why that fails, the string is the same and it does not fail in my machine :S

**Comment by AlfonsoUceda** [comment]
All green :)

**Comment by ronwsmith** [comment]
Released in 3.0.0

**Pull request merged**
