### PR TITLE
Add Ruby 3.3 to CI

### PR DESCRIPTION
**Pull request by MatheusRich**

### CODE REVIEW

**Comment by ronwsmith** [comment]
Looks like running CI exposes the issue reported in https://github.com/oesmith/puffing-billy/issues/341

**Comment by ronwsmith** [comment]
Hopefully your PR will get merged, linking here: https://github.com/igrigorik/em-http-request/pull/358

**Comment by MatheusRich** [comment]
@ronwsmith Cookiejar released a new version. We can update and add Ruby 3.3 to CI now

**Comment by ronwsmith** [comment]
@MatheusRich Looks like there are new CI issues.  Can you take a look?

**Comment by slavingia** [comment]
How's this looking?

**Comment by ronwsmith** [comment]
Addressed in https://github.com/oesmith/puffing-billy/pull/348

**Pull request closed without merging**
