### PR TITLE
Improved semantic versioning of dependencies

### PR DESCRIPTION
**Pull request by Jack12816**
**- What is it good for?**

When specifying runtime dependencies its more useful to stick to the `"~> 1.0", ">= 1.0.4"` syntax to allow installations on that gem with version 1.2.0 as well. Which is completely fine due to semantic versioning. 

Solves situations like this:
```bash
Bundler could not find compatible versions for gem "addressable":
  In snapshot (Gemfile.lock):
    addressable (= 2.5.2)

  In Gemfile:
    capybara (~> 2.15) was resolved to 2.15.4, which depends on
      addressable

    capybara-screenshot (>= 1.0.13, ~> 1.0) was resolved to 1.0.17, which depends on
      launchy was resolved to 2.4.3, which depends on
        addressable (~> 2.3)

    puffing-billy (~> 0.10.1) was resolved to 0.10.1, which depends on
      addressable (~> 2.4.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

[...]

$ bundle update

[..]

Installing addressable 2.4.0 (was 2.5.2)
```

**- What I did**

Changed the runtime dependency version syntax as described. And removed the Gemfile.lock and blacklisted the file in .gitignore. The Travis environment should install a set of gems depending on the running ruby version. Furthermore, I updated PhantomJS to 2.1.1 on Travis to overcome the deprecated warnings and I added the Travis cache for the bundle to speed up the build.

**- A picture of a cute animal (not mandatory but encouraged)**
images

### CODE REVIEW

**Comment by Jack12816** [comment]
Looks like `1.9.3` is broken unrelated.

```bash
Failures:
  1) Watir-specific tests should respond to a stubbed GET request
     Failure/Error: expect(@browser.text).to eq 'Success!'
     
     NameError:
       wrong constant name Watir::Locators::Element::Validator
```

https://travis-ci.org/oesmith/puffing-billy/jobs/287545501

**Comment by ronwsmith** [comment]
@Jack12816 Did you grab the latest code from master yesterday?  That fixed up a Travis issue and I'm hoping it might help your PR too.

**Comment by Jack12816** [comment]
@ronwsmith Mhh, I'm on top of 190077369fa94b0e434d0fa03312e244b782db22

**Comment by ronwsmith** [comment]
There's possibly an issue with the watir-webdriver update.

In the [0.10.1 Travis run](https://travis-ci.org/oesmith/puffing-billy/jobs/287264144), watir-webdriver 0.9.1 was installed without any warnings/issue.

In your PR's run, watir-webdriver 0.9.9 was installed with the following warning:

> With the release of Watir 6.0, the watir-webdriver gem has changed its name
> to watir. Update your dependencies to use "watir", "~> 6.0"

May need to pin the patchlevel or attempt the update to `watir`

**Comment by Jack12816** [comment]
@ronwsmith: I pinned the watir-webdriver gem to 0.9.1. :) 
I updated phantomjs as well and added caching settings for Travis. 

Looks like the watir-webdriver was moved a year ago to the mainline watir
repository. (https://github.com/watir/watir-webdriver) I would recommend 
updating this dev dependency but on a dedicated PR.

Is there anything left on this PR?

**Comment by ronwsmith** [comment]
Looks great @Jack12816!  I'll get this in soon.

**Comment by ronwsmith** [comment]
Released in v0.11.0

**Pull request merged**
