### PR TITLE
WIP: Fix travis CI

### PR DESCRIPTION
**Pull request by jurglic**
Looks like current master is not passing on travis CI.

We need to fix this first before #188 can be merged.

This is a WIP PR at the moment - so I can test travis CI.

### CODE REVIEW

**Comment by jurglic** [comment]
The CI build fails when installing [capybara-webkit](https://travis-ci.org/oesmith/puffing-billy/jobs/238685997) ...

I tried to update QT dependencies - the available version is `4.8` which is not supported by [this gem](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit). I had no success with installing QT 5.x ...

It also leaves the question how could this work before, and suddenly stopped passing...

**Comment by ronwsmith** [comment]
Maybe compare the build steps from the last version of the gem?
https://travis-ci.org/oesmith/puffing-billy/builds/219391774

**Comment by jurglic** [comment]
@ronwsmith As you can see, this is empty commit on top of master - no changes at all. It is still failing on the CI...

**Comment by ronwsmith** [comment]
@jurglic yes, that's why I suggested at looking at the build steps on Travis as that's the only place something may have changed.

**Comment by ronwsmith** [comment]
Travis issues resolved in other PRs

**Pull request closed without merging**
