### PR TITLE
Add driver registration for apparition driver

### PR DESCRIPTION
**Pull request by twalpole**
This PR adds a default registration for the Apparition (Chrome via CDP) driver - https://github.com/twalpole/apparition

### CODE REVIEW

**Comment by ronwsmith** [comment]
@twalpole thanks for the contribution!  Mind removing travis support for ruby 2.0.0-2.2.0 since they aren't supported by apparition, and then adding ruby 2.5.0?

**Comment by twalpole** [comment]
@ronwsmith Done

**Comment by thbar** [comment]
@twalpole I wonder if it's worth adding the fix you provided here https://github.com/twalpole/apparition/issues/2#issuecomment-458807373 to this PR?

**Comment by thbar** [comment]
@twalpole ok so then I suggest it would be good to add a note to the puffing billy readme nearby a section introducing the driver, because this is going to catch people off-guard quite a bit (= all https calls are not proxied, and this will cause problems in some cases, especially if dealing with VCR & payments gateways).

(I can prepare a PR for that little note if the maintainers agree!)

**Pull request merged**
